### ISSUE TITLE
Errors

### ISSUE THREAD

**Issue by jungminchoilab** [Zhiqin-HUANG/confFuse#2]
Hello,

Thanks for sharing the script! I ran defuse (deFuse v0.7.0) for a couple of RNA-seq samples and wanted to apply confFuse to extracted high-confident fusion candidates.
Unfortunately, I am getting erros for both samples as below.
Could you kindly look into this? Please feel free to let me know if you need additional information troubleshooting this.

Best,
Jungmin

```
$ python ~/programs/confFuse/confFuse.py test1/ confFuse_test1 ~/programs/confFuse/artefact_list.tab ~/programs/confFuse/gencode.v19.chr_patch_hapl_scaff.annotation.gtf 
 create directory:confFuse_test1
 Traceback (most recent call last):
   File "/home/jc2545/programs/confFuse/confFuse.py", line 152, in <module>
     if int(occurrences.count(fusion)) >=2 and score<8 and float(maxProportion) < 0.5 and 
 readThough=="N" and alts=="N":				
 ValueError: could not convert string to float: -

$ python ~/programs/confFuse/confFuse.py test2/ confFuse_test2 ~/programs/confFuse/artefact_list.tab ~/programs/confFuse/gencode.v19.chr_patch_hapl_scaff.annotation.gtf 
create directory:confFuse_test2
Traceback (most recent call last):
  File "/home/jc2545/programs/confFuse/confFuse.py", line 175, in <module>
    if int(spanCount) - int(numMultiMap) < 5:
ValueError: invalid literal for int() with base 10: 'N'
```

**Comment by Zhiqin-HUANG** [comment]
Hello Jungmin,

Thanks for your feedback.

The version of deFuse for this paper was V0.6.1. In your description of the
first error, it seems that string value exists in the column 48
"max_repeat_proportion".

In the second error, perhaps your deFuse files contain string in column 51
"num_multi_map" and/or column 57 "span_count".

Should you still not run confFuse successfully, you could send me the
deFuse files. I will try to find a workaround of the problems.

Best,
Zhiqin

**Comment by jungminchoilab** [comment]
Hi Zhiqin,

Thanks for your kind response. I have been trying to fix the errors that I have been getting from defuse before troubleshooting confFuse issues. Unfortunately, the author of defuse is not answering the questions.
Since you developed the post-processing software for defuse, I thought you might have insight what could have caused this issue.

So I have 8 RNA-seq data that I have already run with tophat-fusion and star-fusion. I also wanted to run with defuse+confFuse to maximize the sensitivity. Interestingly, when I ran with defuse, only two of them finished successfully and the rest of them failed in the middle with the same error messages shown below (and those two that generated the expected output files output the errors with confFuse).
I tried with different versions (v0.8.1, v0.7.0 and v0.6.1) and they all resulted in same errors.

Would you kindly look into this and share your thoughts based on your experience? I would be grateful if you can suggest anything.

Thank you for your time!
Jungmin

```
Failure for defuse command:
        /home/jc2545/programs/gmap-2018-02-10/bin/gmap -D /home/jc2545/programs/defuse/scripts/dataset_directory//gmap -d cdna -f psl
  /ycga-ba/ba_sequencers2/scratch/lifton/jc2545/LMS_GATK/rms/rnaseq/defuse_LEYONFF7/jobs/breakpoints.split.001.fa > /ycga-ba/ba_seque
ncers2/scratch/lifton/jc2545/LMS_GATK/rms/rnaseq/defuse_LEYONFF7/jobs/breakpoints.split.001.fa.cdna.psl.tmp
Reason:
        Job command with nonzero return code
Job output:

        The following have been reloaded with a version change:
          1) GCC/5.4.0-2.26 => GCC/6.3.0-2.27
          2) GCCcore/5.4.0 => GCCcore/6.3.0
          3) binutils/2.26-GCCcore-5.4.0 => binutils/2.27-GCCcore-6.3.0

        Running on c17n02
        GMAP version 2018-02-10 called with args: /home/jc2545/programs/gmap-2018-02-10/bin/gmap.avx2 -D /home/jc2545/programs/defuse
/scripts/dataset_directory//gmap -d cdna -f psl /ycga-ba/ba_sequencers2/scratch/lifton/jc2545/LMS_GATK/rms/rnaseq/defuse_LEYONFF7/job
s/breakpoints.split.001.fa
        Checking compiler assumptions for SSE2: 6B8B4567 327B23C6 xor=59F066A1
        Checking compiler assumptions for SSE4.1: -103 -58 max=198 => compiler zero extends
        Checking compiler options for SSE4.2: 6B8B4567 __builtin_clz=1 __builtin_ctz=0 _mm_popcnt_u32=17 __builtin_popcount=17 
        Finished checking compiler assumptions
        Pre-loading compressed genome (oligos)......done (95,425,188 bytes, 23298 pages, 0.12 sec)
        Pre-loading compressed genome (bits)......done (95,425,200 bytes, 23298 pages, 0.05 sec)
        Looking for index files in directory /home/jc2545/programs/defuse/scripts/dataset_directory//gmap/cdna
          Pointers file is cdna.ref153offsets64meta
          Offsets file is cdna.ref153offsets64strm
          Positions file is cdna.ref153positions
        Offsets compression type: bitpack64
        Allocating memory for ref offset pointers, kmer 15, interval 3...Attached new memory for /home/jc2545/programs/defuse/scripts
/dataset_directory//gmap/cdna/cdna.ref153offsets64meta...done (134,217,744 bytes, 0.46 sec)
        Allocating memory for ref offsets, kmer 15, interval 3...Attached new memory for /home/jc2545/programs/defuse/scripts/dataset
_directory//gmap/cdna/cdna.ref153offsets64strm...done (256,547,072 bytes, 0.68 sec)
        Pre-loading ref positions, kmer 15, interval 3......done (336,756,920 bytes, 0.17 sec)
        Looking for local files in directory /home/jc2545/programs/defuse/scripts/dataset_directory//gmap/cdna
          Table file is cdna.ref081loctable
          Pointers file is cdna.ref081locoffsets64meta
          Offsets file is cdna.ref081locoffsets64strm
          Positions file is cdna.ref081locpositions
        Allocating memory for ref offset pointers, kmer 8, interval 1...Attached new memory for /home/jc2545/programs/defuse/scripts/
dataset_directory//gmap/cdna/cdna.ref081locoffsets64meta...done (15,904,768 bytes, 0.17 sec)
        Allocating memory for ref offsets, kmer 8, interval 1...Attached new memory for /home/jc2545/programs/defuse/scripts/dataset_
directory//gmap/cdna/cdna.ref081locoffsets64strm...done (165,047,856 bytes, 1.03 sec)
        Attached new memory for /home/jc2545/programs/defuse/scripts/dataset_directory//gmap/cdna/cdna.ref081loctable...done (31,064 
bytes, 0.00 sec)
        Allocating memory for ref positions, kmer 8, interval 1...Attached new memory for /home/jc2545/programs/defuse/scripts/datase
t_directory//gmap/cdna/cdna.ref081locpositions...done (506,890,222 bytes, 1.47 sec)
```

**Comment by Zhiqin-HUANG** [comment]
Hi Jungmin,

I haven't seen such an error before. I therefore could not give you much help. Perhaps you could find some information in the followin links:

https://sourceforge.net/p/defuse/discussion/deFuseHelp/thread/1742c77f/
https://bitbucket.org/dranew/defuse/issues/24/error-on-run

Best,
Zhiqin
